# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: selfhostedap

steps:
- task: Maven@3
  inputs:
    mavenVersionOption: 'path'
    mavenDirectory: '/mnt/c/Programs/apache-maven-3.6.1'
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx2048m'
    javaHomeOption: 'path'
    jdkDirectory: '/usr/bin'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
